version: '3'

networks:
  replicated_log_bridge:


services:
  master:
    image: replicated_log:v2
    command: [ "python", "master.py" ]
    ports:
      - "5000:5000"
    networks:
      - replicated_log_bridge
    environment:
      - SECONDARY1_URL=${SECONDARY1_URL}
      - SECONDARY2_URL=${SECONDARY2_URL}

  secondary1:
    image: replicated_log:v2
    command: [ "python", "secondary.py" ]
    ports:
      - "5001:5000"
    networks:
      - replicated_log_bridge
    environment:
      - SECONDARY_DELAY=${SECONDARY1_DELAY}

  secondary2:
    image: replicated_log:v2
    command: [ "python", "secondary.py" ]
    ports:
      - "5002:5000"
    networks:
      - replicated_log_bridge
    environment:
      - SECONDARY_DELAY=${SECONDARY2_DELAY}
